name = "skeb-info"
compatibility_date = "2025-04-28"
main = "worker.js"
type = "esmodule"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./static"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[[unsafe.bindings]]
name = "USER_INFO_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }

[[unsafe.bindings]]
name = "WORKS_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 5, period = 60 }